# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.5
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

##   Generated via the command line invocation:
##	 swig -r beagle.i


#                         srun.swg                            #
#
# This is the basic code that is needed at run time within R to
# provide and define the relevant classes.  It is included
# automatically in the generated code by copying the contents of
# srun.swg into the newly created binding code.


# This could be provided as a separate run-time library but this
# approach allows the code to to be included directly into the
# generated bindings and so removes the need to have and install an
# additional library.  We may however end up with multiple copies of
# this and some confusion at run-time as to which class to use. This
# is an issue when we use NAMESPACES as we may need to export certain
# classes.

######################################################################

if(length(getClassDef("RSWIGStruct")) == 0) 
  setClass("RSWIGStruct", representation("VIRTUAL"))



if(length(getClassDef("ExternalReference")) == 0) 
# Should be virtual but this means it loses its slots currently
#representation("VIRTUAL")
  setClass("ExternalReference", representation( ref = "externalptr"))



if(length(getClassDef("NativeRoutinePointer")) == 0) 
  setClass("NativeRoutinePointer", 
              representation(parameterTypes = "character",
                             returnType = "character",
                             "VIRTUAL"), 
              contains = "ExternalReference")

if(length(getClassDef("CRoutinePointer")) == 0) 
  setClass("CRoutinePointer", contains = "NativeRoutinePointer")


if(length(getClassDef("EnumerationValue")) == 0) 
  setClass("EnumerationValue", contains = "integer")


if(!isGeneric("copyToR")) 
 setGeneric("copyToR",
            function(value, obj = new(gsub("Ref$", "", class(value)))) 
               standardGeneric("copyToR"
           ))

setGeneric("delete", function(obj) standardGeneric("delete"))


SWIG_createNewRef = 
function(className, ..., append = TRUE)
{
  f = get(paste("new", className, sep = "_"), mode = "function")

  f(...)
}

if(!isGeneric("copyToC")) 
 setGeneric("copyToC", 
             function(value, obj = RSWIG_createNewRef(class(value)))
              standardGeneric("copyToC"
            ))


# 
defineEnumeration =
function(name, .values, where = topenv(parent.frame()), suffix = "Value")
{
   # Mirror the class definitions via the E analogous to .__C__
  defName = paste(".__E__", name, sep = "")
  assign(defName,  .values,  envir = where)

  if(nchar(suffix))
    name = paste(name, suffix, sep = "")

  setClass(name, contains = "EnumerationValue", where = where)
}

enumToInteger <- function(name,type)
{
   if (is.character(name)) {
   ans <- as.integer(get(paste(".__E__", type, sep = ""))[name])
   if (is.na(ans)) {warning("enum not found ", name, " ", type)}
   ans
   } 
}

enumFromInteger =
function(i,type)
{
  itemlist <- get(paste(".__E__", type, sep=""))
  names(itemlist)[match(i, itemlist)]
}

coerceIfNotSubclass =
function(obj, type) 
{
    if(!is(obj, type)) {as(obj, type)} else obj
}


setClass("SWIGArray", representation(dims = "integer"), contains = "ExternalReference")

setMethod("length", "SWIGArray", function(x) x@dims[1])


defineEnumeration("SCopyReferences",
                   .values = c( "FALSE" = 0, "TRUE" = 1, "DEEP" = 2))

assert = 
function(condition, message = "")
{
  if(!condition)
    stop(message)

  TRUE
}


if(FALSE) {
print.SWIGFunction =
function(x, ...)
 {
 }
}


#######################################################################

R_SWIG_getCallbackFunctionStack =
function()
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_debug_getCallbackFunctionData")
}

R_SWIG_addCallbackFunctionStack =
function(fun, userData = NULL)
{
    # No PACKAGE argument as we don't know what the DLL is.
  .Call("R_SWIG_R_pushCallbackFunctionData", fun, userData)
}


#######################################################################


setClass('_p_BeagleInstanceDetails', contains = 'ExternalReference')
setClass("BeagleInstanceDetails",
    representation(
        resourceNumber = "integer",
        resourceName = "character",
        implName = "character",
        implDescription = "character",
        flags = "integer"),
        contains = "RSWIGStruct")


# End class BeagleInstanceDetails

setClass('_p_BeagleInstanceDetails', contains = 'ExternalReference')
setClass('_p_BeagleResource', contains = 'ExternalReference')
setClass("BeagleResource",
    representation(
        name = "character",
        description = "character",
        supportFlags = "integer",
        requiredFlags = "integer"),
        contains = "RSWIGStruct")


# End class BeagleResource

setClass('_p_BeagleResource', contains = 'ExternalReference')
setClass('_p_BeagleResourceList', contains = 'ExternalReference')
setClass("BeagleResourceList",
    representation(
        length = "integer"),
        contains = "RSWIGStruct")


# End class BeagleResourceList

setClass('_p_BeagleResourceList', contains = 'ExternalReference')
setClass('_p_BeagleOperation', contains = 'ExternalReference')
setClass("BeagleOperation",
    representation(
        destinationPartials = "integer",
        destinationScaleWrite = "integer",
        destinationScaleRead = "integer",
        child1Partials = "integer",
        child1TransitionMatrix = "integer",
        child2Partials = "integer",
        child2TransitionMatrix = "integer"),
        contains = "RSWIGStruct")


# End class BeagleOperation

setClass('_p_BeagleOperation', contains = 'ExternalReference')



setMethod('[', "ExternalReference",
function(x,i,j, ..., drop=TRUE) 
if (!is.null(x$"__getitem__")) 
sapply(i, function(n) x$"__getitem__"(i=as.integer(n-1))))

setMethod('[<-' , "ExternalReference",
function(x,i,j, ..., value) 
if (!is.null(x$"__setitem__")) {
sapply(1:length(i), function(n) 
x$"__setitem__"(i=as.integer(i[n]-1), x=value[n]))
x
})

setAs('ExternalReference', 'character',
function(from) {if (!is.null(from$"__str__")) from$"__str__"()})

setMethod('print', 'ExternalReference',
function(x) {print(as(x, "character"))})

# Start of new_intp

`new_intp` = function()
{
  ;ans = .Call('R_swig_new_intp', PACKAGE='beagle');
  ans <- new("_p_int", ref=ans) ;
  
  ans
  
}

attr(`new_intp`, 'returnType') = 'integer'
class(`new_intp`) = c("SWIGFunction", class('new_intp'))

# Start of copy_intp

`copy_intp` = function(value)
{
  value = as.integer(value);
  
  if(length(value) > 1) {
    warning("using only the first element of value");
  };
  
  ;ans = .Call('R_swig_copy_intp', value, PACKAGE='beagle');
  ans <- new("_p_int", ref=ans) ;
  
  ans
  
}

attr(`copy_intp`, 'returnType') = 'integer'
attr(`copy_intp`, "inputTypes") = c('integer')
class(`copy_intp`) = c("SWIGFunction", class('copy_intp'))

# Start of delete_intp

`delete_intp` = function(obj)
{
  obj = as.integer(obj);
  ;.Call('R_swig_delete_intp', obj, PACKAGE='beagle');
  
}

attr(`delete_intp`, 'returnType') = 'void'
attr(`delete_intp`, "inputTypes") = c('integer')
class(`delete_intp`) = c("SWIGFunction", class('delete_intp'))

# Start of intp_assign

`intp_assign` = function(obj, value)
{
  obj = as.integer(obj);
  value = as.integer(value);
  
  if(length(value) > 1) {
    warning("using only the first element of value");
  };
  
  ;.Call('R_swig_intp_assign', obj, value, PACKAGE='beagle');
  
}

attr(`intp_assign`, 'returnType') = 'void'
attr(`intp_assign`, "inputTypes") = c('integer', 'integer')
class(`intp_assign`) = c("SWIGFunction", class('intp_assign'))

# Start of intp_value

`intp_value` = function(obj, .copy = FALSE)
{
  obj = as.integer(obj);
  ;.Call('R_swig_intp_value', obj, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`intp_value`, 'returnType') = 'integer'
attr(`intp_value`, "inputTypes") = c('integer')
class(`intp_value`) = c("SWIGFunction", class('intp_value'))

# Start of new_doublep

`new_doublep` = function()
{
  ;.Call('R_swig_new_doublep', PACKAGE='beagle');
  
}

attr(`new_doublep`, 'returnType') = 'numeric'
class(`new_doublep`) = c("SWIGFunction", class('new_doublep'))

# Start of copy_doublep

`copy_doublep` = function(value)
{
  ;.Call('R_swig_copy_doublep', value, PACKAGE='beagle');
  
}

attr(`copy_doublep`, 'returnType') = 'numeric'
attr(`copy_doublep`, "inputTypes") = c('numeric')
class(`copy_doublep`) = c("SWIGFunction", class('copy_doublep'))

# Start of delete_doublep

`delete_doublep` = function(obj)
{
  ;.Call('R_swig_delete_doublep', obj, PACKAGE='beagle');
  
}

attr(`delete_doublep`, 'returnType') = 'void'
attr(`delete_doublep`, "inputTypes") = c('numeric')
class(`delete_doublep`) = c("SWIGFunction", class('delete_doublep'))

# Start of doublep_assign

`doublep_assign` = function(obj, value)
{
  ;.Call('R_swig_doublep_assign', obj, value, PACKAGE='beagle');
  
}

attr(`doublep_assign`, 'returnType') = 'void'
attr(`doublep_assign`, "inputTypes") = c('numeric', 'numeric')
class(`doublep_assign`) = c("SWIGFunction", class('doublep_assign'))

# Start of doublep_value

`doublep_value` = function(obj, .copy = FALSE)
{
  ;.Call('R_swig_doublep_value', obj, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`doublep_value`, 'returnType') = 'numeric'
attr(`doublep_value`, "inputTypes") = c('numeric')
class(`doublep_value`) = c("SWIGFunction", class('doublep_value'))

# Start of new_intArray

`new_intArray` = function(nelements)
{
  nelements = as.integer(nelements);
  
  if(length(nelements) > 1) {
    warning("using only the first element of nelements");
  };
  
  ;ans = .Call('R_swig_new_intArray', nelements, PACKAGE='beagle');
  ans <- new("_p_int", ref=ans) ;
  
  ans
  
}

attr(`new_intArray`, 'returnType') = 'integer'
attr(`new_intArray`, "inputTypes") = c('integer')
class(`new_intArray`) = c("SWIGFunction", class('new_intArray'))

# Start of delete_intArray

`delete_intArray` = function(ary)
{
  ary = as.integer(ary);
  ;.Call('R_swig_delete_intArray', ary, PACKAGE='beagle');
  
}

attr(`delete_intArray`, 'returnType') = 'void'
attr(`delete_intArray`, "inputTypes") = c('integer')
class(`delete_intArray`) = c("SWIGFunction", class('delete_intArray'))

# Start of intArray_getitem

`intArray_getitem` = function(ary, index, .copy = FALSE)
{
  ary = as.integer(ary);
  index = as.integer(index);
  
  if(length(index) > 1) {
    warning("using only the first element of index");
  };
  
  ;.Call('R_swig_intArray_getitem', ary, index, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`intArray_getitem`, 'returnType') = 'integer'
attr(`intArray_getitem`, "inputTypes") = c('integer', 'integer')
class(`intArray_getitem`) = c("SWIGFunction", class('intArray_getitem'))

# Start of intArray_setitem

`intArray_setitem` = function(ary, index, value)
{
  ary = as.integer(ary);
  index = as.integer(index);
  
  if(length(index) > 1) {
    warning("using only the first element of index");
  };
  
  value = as.integer(value);
  
  if(length(value) > 1) {
    warning("using only the first element of value");
  };
  
  ;.Call('R_swig_intArray_setitem', ary, index, value, PACKAGE='beagle');
  
}

attr(`intArray_setitem`, 'returnType') = 'void'
attr(`intArray_setitem`, "inputTypes") = c('integer', 'integer', 'integer')
class(`intArray_setitem`) = c("SWIGFunction", class('intArray_setitem'))

# Start of new_doubleArray

`new_doubleArray` = function(nelements)
{
  nelements = as.integer(nelements);
  
  if(length(nelements) > 1) {
    warning("using only the first element of nelements");
  };
  
  ;.Call('R_swig_new_doubleArray', nelements, PACKAGE='beagle');
  
}

attr(`new_doubleArray`, 'returnType') = 'numeric'
attr(`new_doubleArray`, "inputTypes") = c('integer')
class(`new_doubleArray`) = c("SWIGFunction", class('new_doubleArray'))

# Start of delete_doubleArray

`delete_doubleArray` = function(ary)
{
  ;.Call('R_swig_delete_doubleArray', ary, PACKAGE='beagle');
  
}

attr(`delete_doubleArray`, 'returnType') = 'void'
attr(`delete_doubleArray`, "inputTypes") = c('numeric')
class(`delete_doubleArray`) = c("SWIGFunction", class('delete_doubleArray'))

# Start of doubleArray_getitem

`doubleArray_getitem` = function(ary, index, .copy = FALSE)
{
  index = as.integer(index);
  
  if(length(index) > 1) {
    warning("using only the first element of index");
  };
  
  ;.Call('R_swig_doubleArray_getitem', ary, index, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`doubleArray_getitem`, 'returnType') = 'numeric'
attr(`doubleArray_getitem`, "inputTypes") = c('numeric', 'integer')
class(`doubleArray_getitem`) = c("SWIGFunction", class('doubleArray_getitem'))

# Start of doubleArray_setitem

`doubleArray_setitem` = function(ary, index, value)
{
  index = as.integer(index);
  
  if(length(index) > 1) {
    warning("using only the first element of index");
  };
  
  
  ;.Call('R_swig_doubleArray_setitem', ary, index, value, PACKAGE='beagle');
  
}

attr(`doubleArray_setitem`, 'returnType') = 'void'
attr(`doubleArray_setitem`, "inputTypes") = c('numeric', 'integer', 'numeric')
class(`doubleArray_setitem`) = c("SWIGFunction", class('doubleArray_setitem'))

defineEnumeration('_BeagleReturnCodes',
                    .values = c(
                        'BEAGLE_SUCCESS' = 0, 
                        'BEAGLE_ERROR_GENERAL' = -1, 
                        'BEAGLE_ERROR_OUT_OF_MEMORY' = -2, 
                        'BEAGLE_ERROR_UNIDENTIFIED_EXCEPTION' = -3, 
                        'BEAGLE_ERROR_UNINITIALIZED_INSTANCE' = -4, 
                        'BEAGLE_ERROR_OUT_OF_RANGE' = -5, 
                        'BEAGLE_ERROR_NO_RESOURCE' = -6, 
                        'BEAGLE_ERROR_NO_IMPLEMENTATION' = -7, 
                        'BEAGLE_ERROR_FLOATING_POINT' = -8
))
defineEnumeration('_BeagleFlags',
                    .values = c(
                        'BEAGLE_FLAG_PRECISION_SINGLE' = 1, 
                        'BEAGLE_FLAG_PRECISION_DOUBLE' = 1, 
                        'BEAGLE_FLAG_COMPUTATION_SYNCH' = 1, 
                        'BEAGLE_FLAG_COMPUTATION_ASYNCH' = 1, 
                        'BEAGLE_FLAG_EIGEN_REAL' = 1, 
                        'BEAGLE_FLAG_EIGEN_COMPLEX' = 1, 
                        'BEAGLE_FLAG_SCALING_MANUAL' = 1, 
                        'BEAGLE_FLAG_SCALING_AUTO' = 1, 
                        'BEAGLE_FLAG_SCALING_ALWAYS' = 1, 
                        'BEAGLE_FLAG_SCALING_DYNAMIC' = 1, 
                        'BEAGLE_FLAG_SCALERS_RAW' = 1, 
                        'BEAGLE_FLAG_SCALERS_LOG' = 1, 
                        'BEAGLE_FLAG_INVEVEC_STANDARD' = 1, 
                        'BEAGLE_FLAG_INVEVEC_TRANSPOSED' = 1, 
                        'BEAGLE_FLAG_VECTOR_SSE' = 1, 
                        'BEAGLE_FLAG_VECTOR_NONE' = 1, 
                        'BEAGLE_FLAG_THREADING_OPENMP' = 1, 
                        'BEAGLE_FLAG_THREADING_NONE' = 1, 
                        'BEAGLE_FLAG_PROCESSOR_CPU' = 1, 
                        'BEAGLE_FLAG_PROCESSOR_GPU' = 1, 
                        'BEAGLE_FLAG_PROCESSOR_FPGA' = 1, 
                        'BEAGLE_FLAG_PROCESSOR_CELL' = 1, 
                        'BEAGLE_FLAG_FRAMEWORK_CUDA' = 1, 
                        'BEAGLE_FLAG_FRAMEWORK_OPENCL' = 1
))
defineEnumeration('_BeagleOpCodes',
                    .values = c(
                        'BEAGLE_OP_COUNT' = 7, 
                        'BEAGLE_OP_NONE' = -1
))
# Start of BeagleInstanceDetails_resourceNumber_set

`BeagleInstanceDetails_resourceNumber_set` = function(self, s_resourceNumber)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_resourceNumber = as.integer(s_resourceNumber);
  
  if(length(s_resourceNumber) > 1) {
    warning("using only the first element of s_resourceNumber");
  };
  
  ;.Call('R_swig_BeagleInstanceDetails_resourceNumber_set', self, s_resourceNumber, PACKAGE='beagle');
  
}

attr(`BeagleInstanceDetails_resourceNumber_set`, 'returnType') = 'void'
attr(`BeagleInstanceDetails_resourceNumber_set`, "inputTypes") = c('_p_BeagleInstanceDetails', 'integer')
class(`BeagleInstanceDetails_resourceNumber_set`) = c("SWIGFunction", class('BeagleInstanceDetails_resourceNumber_set'))

# Start of BeagleInstanceDetails_resourceNumber_get

`BeagleInstanceDetails_resourceNumber_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_BeagleInstanceDetails_resourceNumber_get', self, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`BeagleInstanceDetails_resourceNumber_get`, 'returnType') = 'integer'
attr(`BeagleInstanceDetails_resourceNumber_get`, "inputTypes") = c('_p_BeagleInstanceDetails')
class(`BeagleInstanceDetails_resourceNumber_get`) = c("SWIGFunction", class('BeagleInstanceDetails_resourceNumber_get'))

# Start of BeagleInstanceDetails_resourceName_set

`BeagleInstanceDetails_resourceName_set` = function(self, s_resourceName)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_resourceName = as(s_resourceName, "character"); 
  ;.Call('R_swig_BeagleInstanceDetails_resourceName_set', self, s_resourceName, PACKAGE='beagle');
  
}

attr(`BeagleInstanceDetails_resourceName_set`, 'returnType') = 'void'
attr(`BeagleInstanceDetails_resourceName_set`, "inputTypes") = c('_p_BeagleInstanceDetails', 'character')
class(`BeagleInstanceDetails_resourceName_set`) = c("SWIGFunction", class('BeagleInstanceDetails_resourceName_set'))

# Start of BeagleInstanceDetails_resourceName_get

`BeagleInstanceDetails_resourceName_get` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_BeagleInstanceDetails_resourceName_get', self, PACKAGE='beagle');
  
}

attr(`BeagleInstanceDetails_resourceName_get`, 'returnType') = 'character'
attr(`BeagleInstanceDetails_resourceName_get`, "inputTypes") = c('_p_BeagleInstanceDetails')
class(`BeagleInstanceDetails_resourceName_get`) = c("SWIGFunction", class('BeagleInstanceDetails_resourceName_get'))

# Start of BeagleInstanceDetails_implName_set

`BeagleInstanceDetails_implName_set` = function(self, s_implName)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_implName = as(s_implName, "character"); 
  ;.Call('R_swig_BeagleInstanceDetails_implName_set', self, s_implName, PACKAGE='beagle');
  
}

attr(`BeagleInstanceDetails_implName_set`, 'returnType') = 'void'
attr(`BeagleInstanceDetails_implName_set`, "inputTypes") = c('_p_BeagleInstanceDetails', 'character')
class(`BeagleInstanceDetails_implName_set`) = c("SWIGFunction", class('BeagleInstanceDetails_implName_set'))

# Start of BeagleInstanceDetails_implName_get

`BeagleInstanceDetails_implName_get` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_BeagleInstanceDetails_implName_get', self, PACKAGE='beagle');
  
}

attr(`BeagleInstanceDetails_implName_get`, 'returnType') = 'character'
attr(`BeagleInstanceDetails_implName_get`, "inputTypes") = c('_p_BeagleInstanceDetails')
class(`BeagleInstanceDetails_implName_get`) = c("SWIGFunction", class('BeagleInstanceDetails_implName_get'))

# Start of BeagleInstanceDetails_implDescription_set

`BeagleInstanceDetails_implDescription_set` = function(self, s_implDescription)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_implDescription = as(s_implDescription, "character"); 
  ;.Call('R_swig_BeagleInstanceDetails_implDescription_set', self, s_implDescription, PACKAGE='beagle');
  
}

attr(`BeagleInstanceDetails_implDescription_set`, 'returnType') = 'void'
attr(`BeagleInstanceDetails_implDescription_set`, "inputTypes") = c('_p_BeagleInstanceDetails', 'character')
class(`BeagleInstanceDetails_implDescription_set`) = c("SWIGFunction", class('BeagleInstanceDetails_implDescription_set'))

# Start of BeagleInstanceDetails_implDescription_get

`BeagleInstanceDetails_implDescription_get` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_BeagleInstanceDetails_implDescription_get', self, PACKAGE='beagle');
  
}

attr(`BeagleInstanceDetails_implDescription_get`, 'returnType') = 'character'
attr(`BeagleInstanceDetails_implDescription_get`, "inputTypes") = c('_p_BeagleInstanceDetails')
class(`BeagleInstanceDetails_implDescription_get`) = c("SWIGFunction", class('BeagleInstanceDetails_implDescription_get'))

# Start of BeagleInstanceDetails_flags_set

`BeagleInstanceDetails_flags_set` = function(self, s_flags)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_flags = as.integer(s_flags);
  
  if(length(s_flags) > 1) {
    warning("using only the first element of s_flags");
  };
  
  ;.Call('R_swig_BeagleInstanceDetails_flags_set', self, s_flags, PACKAGE='beagle');
  
}

attr(`BeagleInstanceDetails_flags_set`, 'returnType') = 'void'
attr(`BeagleInstanceDetails_flags_set`, "inputTypes") = c('_p_BeagleInstanceDetails', 'integer')
class(`BeagleInstanceDetails_flags_set`) = c("SWIGFunction", class('BeagleInstanceDetails_flags_set'))

# Start of BeagleInstanceDetails_flags_get

`BeagleInstanceDetails_flags_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_BeagleInstanceDetails_flags_get', self, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`BeagleInstanceDetails_flags_get`, 'returnType') = 'integer'
attr(`BeagleInstanceDetails_flags_get`, "inputTypes") = c('_p_BeagleInstanceDetails')
class(`BeagleInstanceDetails_flags_get`) = c("SWIGFunction", class('BeagleInstanceDetails_flags_get'))

# Start of new_BeagleInstanceDetails

`BeagleInstanceDetails` = function()
{
  ;ans = .Call('R_swig_new_BeagleInstanceDetails', PACKAGE='beagle');
  ans <- new("_p_BeagleInstanceDetails", ref=ans) ;
  
  reg.finalizer(ans@ref, delete_BeagleInstanceDetails)
  ans
  
}

attr(`BeagleInstanceDetails`, 'returnType') = '_p_BeagleInstanceDetails'
class(`BeagleInstanceDetails`) = c("SWIGFunction", class('BeagleInstanceDetails'))

# Start of delete_BeagleInstanceDetails

`delete_BeagleInstanceDetails` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_delete_BeagleInstanceDetails', self, PACKAGE='beagle');
  
}

attr(`delete_BeagleInstanceDetails`, 'returnType') = 'void'
attr(`delete_BeagleInstanceDetails`, "inputTypes") = c('_p_BeagleInstanceDetails')
class(`delete_BeagleInstanceDetails`) = c("SWIGFunction", class('delete_BeagleInstanceDetails'))

# Start of accessor method for BeagleInstanceDetails
setMethod('$', '_p_BeagleInstanceDetails', function(x, name)

{
  accessorFuns = list('resourceNumber' = BeagleInstanceDetails_resourceNumber_get, 'resourceName' = BeagleInstanceDetails_resourceName_get, 'implName' = BeagleInstanceDetails_implName_get, 'implDescription' = BeagleInstanceDetails_implDescription_get, 'flags' = BeagleInstanceDetails_flags_get);
  vaccessors = c('resourceNumber', 'resourceName', 'implName', 'implDescription', 'flags');
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  if (is.na(match(name, vaccessors))) function(...){
    f(x, ...)
  } else f(x);
}


);
# end of accessor method for BeagleInstanceDetails
# Start of accessor method for BeagleInstanceDetails
setMethod('$<-', '_p_BeagleInstanceDetails', function(x, name, value)

{
  accessorFuns = list('resourceNumber' = BeagleInstanceDetails_resourceNumber_set, 'resourceName' = BeagleInstanceDetails_resourceName_set, 'implName' = BeagleInstanceDetails_implName_set, 'implDescription' = BeagleInstanceDetails_implDescription_set, 'flags' = BeagleInstanceDetails_flags_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
setMethod('[[<-', c('_p_BeagleInstanceDetails', 'character'),function(x, i, j, ..., value)

{
  name = i;
  accessorFuns = list('resourceNumber' = BeagleInstanceDetails_resourceNumber_set, 'resourceName' = BeagleInstanceDetails_resourceName_set, 'implName' = BeagleInstanceDetails_implName_set, 'implDescription' = BeagleInstanceDetails_implDescription_set, 'flags' = BeagleInstanceDetails_flags_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
# end of accessor method for BeagleInstanceDetails
setMethod('delete', '_p_BeagleInstanceDetails', function(obj) {delete_BeagleInstanceDetails(obj)})
# Start definition of copy functions & methods for BeagleInstanceDetails
CopyToR_BeagleInstanceDetails = function(value, obj = new("BeagleInstanceDetails"))
{
  obj@resourceNumber = value$resourceNumber;
  obj@resourceName = value$resourceName;
  obj@implName = value$implName;
  obj@implDescription = value$implDescription;
  obj@flags = value$flags;
  obj;
}



CopyToC_BeagleInstanceDetails = function(value, obj)
{
  obj$resourceNumber = value@resourceNumber;
  obj$resourceName = value@resourceName;
  obj$implName = value@implName;
  obj$implDescription = value@implDescription;
  obj$flags = value@flags;
  obj
}



# Start definition of copy methods for BeagleInstanceDetails
setMethod('copyToR', '_p_BeagleInstanceDetails', CopyToR_BeagleInstanceDetails);
setMethod('copyToC', 'BeagleInstanceDetails', CopyToC_BeagleInstanceDetails);

# End definition of copy methods for BeagleInstanceDetails
# End definition of copy functions & methods for BeagleInstanceDetails
# Start of BeagleResource_name_set

`BeagleResource_name_set` = function(self, s_name)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_name = as(s_name, "character"); 
  ;.Call('R_swig_BeagleResource_name_set', self, s_name, PACKAGE='beagle');
  
}

attr(`BeagleResource_name_set`, 'returnType') = 'void'
attr(`BeagleResource_name_set`, "inputTypes") = c('_p_BeagleResource', 'character')
class(`BeagleResource_name_set`) = c("SWIGFunction", class('BeagleResource_name_set'))

# Start of BeagleResource_name_get

`BeagleResource_name_get` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_BeagleResource_name_get', self, PACKAGE='beagle');
  
}

attr(`BeagleResource_name_get`, 'returnType') = 'character'
attr(`BeagleResource_name_get`, "inputTypes") = c('_p_BeagleResource')
class(`BeagleResource_name_get`) = c("SWIGFunction", class('BeagleResource_name_get'))

# Start of BeagleResource_description_set

`BeagleResource_description_set` = function(self, s_description)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_description = as(s_description, "character"); 
  ;.Call('R_swig_BeagleResource_description_set', self, s_description, PACKAGE='beagle');
  
}

attr(`BeagleResource_description_set`, 'returnType') = 'void'
attr(`BeagleResource_description_set`, "inputTypes") = c('_p_BeagleResource', 'character')
class(`BeagleResource_description_set`) = c("SWIGFunction", class('BeagleResource_description_set'))

# Start of BeagleResource_description_get

`BeagleResource_description_get` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_BeagleResource_description_get', self, PACKAGE='beagle');
  
}

attr(`BeagleResource_description_get`, 'returnType') = 'character'
attr(`BeagleResource_description_get`, "inputTypes") = c('_p_BeagleResource')
class(`BeagleResource_description_get`) = c("SWIGFunction", class('BeagleResource_description_get'))

# Start of BeagleResource_supportFlags_set

`BeagleResource_supportFlags_set` = function(self, s_supportFlags)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_supportFlags = as.integer(s_supportFlags);
  
  if(length(s_supportFlags) > 1) {
    warning("using only the first element of s_supportFlags");
  };
  
  ;.Call('R_swig_BeagleResource_supportFlags_set', self, s_supportFlags, PACKAGE='beagle');
  
}

attr(`BeagleResource_supportFlags_set`, 'returnType') = 'void'
attr(`BeagleResource_supportFlags_set`, "inputTypes") = c('_p_BeagleResource', 'integer')
class(`BeagleResource_supportFlags_set`) = c("SWIGFunction", class('BeagleResource_supportFlags_set'))

# Start of BeagleResource_supportFlags_get

`BeagleResource_supportFlags_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_BeagleResource_supportFlags_get', self, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`BeagleResource_supportFlags_get`, 'returnType') = 'integer'
attr(`BeagleResource_supportFlags_get`, "inputTypes") = c('_p_BeagleResource')
class(`BeagleResource_supportFlags_get`) = c("SWIGFunction", class('BeagleResource_supportFlags_get'))

# Start of BeagleResource_requiredFlags_set

`BeagleResource_requiredFlags_set` = function(self, s_requiredFlags)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_requiredFlags = as.integer(s_requiredFlags);
  
  if(length(s_requiredFlags) > 1) {
    warning("using only the first element of s_requiredFlags");
  };
  
  ;.Call('R_swig_BeagleResource_requiredFlags_set', self, s_requiredFlags, PACKAGE='beagle');
  
}

attr(`BeagleResource_requiredFlags_set`, 'returnType') = 'void'
attr(`BeagleResource_requiredFlags_set`, "inputTypes") = c('_p_BeagleResource', 'integer')
class(`BeagleResource_requiredFlags_set`) = c("SWIGFunction", class('BeagleResource_requiredFlags_set'))

# Start of BeagleResource_requiredFlags_get

`BeagleResource_requiredFlags_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_BeagleResource_requiredFlags_get', self, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`BeagleResource_requiredFlags_get`, 'returnType') = 'integer'
attr(`BeagleResource_requiredFlags_get`, "inputTypes") = c('_p_BeagleResource')
class(`BeagleResource_requiredFlags_get`) = c("SWIGFunction", class('BeagleResource_requiredFlags_get'))

# Start of new_BeagleResource

`BeagleResource` = function()
{
  ;ans = .Call('R_swig_new_BeagleResource', PACKAGE='beagle');
  ans <- new("_p_BeagleResource", ref=ans) ;
  
  reg.finalizer(ans@ref, delete_BeagleResource)
  ans
  
}

attr(`BeagleResource`, 'returnType') = '_p_BeagleResource'
class(`BeagleResource`) = c("SWIGFunction", class('BeagleResource'))

# Start of delete_BeagleResource

`delete_BeagleResource` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_delete_BeagleResource', self, PACKAGE='beagle');
  
}

attr(`delete_BeagleResource`, 'returnType') = 'void'
attr(`delete_BeagleResource`, "inputTypes") = c('_p_BeagleResource')
class(`delete_BeagleResource`) = c("SWIGFunction", class('delete_BeagleResource'))

# Start of accessor method for BeagleResource
setMethod('$', '_p_BeagleResource', function(x, name)

{
  accessorFuns = list('name' = BeagleResource_name_get, 'description' = BeagleResource_description_get, 'supportFlags' = BeagleResource_supportFlags_get, 'requiredFlags' = BeagleResource_requiredFlags_get);
  vaccessors = c('name', 'description', 'supportFlags', 'requiredFlags');
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  if (is.na(match(name, vaccessors))) function(...){
    f(x, ...)
  } else f(x);
}


);
# end of accessor method for BeagleResource
# Start of accessor method for BeagleResource
setMethod('$<-', '_p_BeagleResource', function(x, name, value)

{
  accessorFuns = list('name' = BeagleResource_name_set, 'description' = BeagleResource_description_set, 'supportFlags' = BeagleResource_supportFlags_set, 'requiredFlags' = BeagleResource_requiredFlags_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
setMethod('[[<-', c('_p_BeagleResource', 'character'),function(x, i, j, ..., value)

{
  name = i;
  accessorFuns = list('name' = BeagleResource_name_set, 'description' = BeagleResource_description_set, 'supportFlags' = BeagleResource_supportFlags_set, 'requiredFlags' = BeagleResource_requiredFlags_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
# end of accessor method for BeagleResource
setMethod('delete', '_p_BeagleResource', function(obj) {delete_BeagleResource(obj)})
# Start definition of copy functions & methods for BeagleResource
CopyToR_BeagleResource = function(value, obj = new("BeagleResource"))
{
  obj@name = value$name;
  obj@description = value$description;
  obj@supportFlags = value$supportFlags;
  obj@requiredFlags = value$requiredFlags;
  obj;
}



CopyToC_BeagleResource = function(value, obj)
{
  obj$name = value@name;
  obj$description = value@description;
  obj$supportFlags = value@supportFlags;
  obj$requiredFlags = value@requiredFlags;
  obj
}



# Start definition of copy methods for BeagleResource
setMethod('copyToR', '_p_BeagleResource', CopyToR_BeagleResource);
setMethod('copyToC', 'BeagleResource', CopyToC_BeagleResource);

# End definition of copy methods for BeagleResource
# End definition of copy functions & methods for BeagleResource
# Start of BeagleResourceList_list_set

`BeagleResourceList_list_set` = function(self, s_list)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  if (inherits(s_list, "ExternalReference")) s_list = slot(s_list,"ref") 
  ;.Call('R_swig_BeagleResourceList_list_set', self, s_list, PACKAGE='beagle');
  
}

attr(`BeagleResourceList_list_set`, 'returnType') = 'void'
attr(`BeagleResourceList_list_set`, "inputTypes") = c('_p_BeagleResourceList', '_p_BeagleResource')
class(`BeagleResourceList_list_set`) = c("SWIGFunction", class('BeagleResourceList_list_set'))

# Start of BeagleResourceList_list_get

`BeagleResourceList_list_get` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;ans = .Call('R_swig_BeagleResourceList_list_get', self, PACKAGE='beagle');
  ans <- new("_p_BeagleResource", ref=ans) ;
  
  ans
  
}

attr(`BeagleResourceList_list_get`, 'returnType') = '_p_BeagleResource'
attr(`BeagleResourceList_list_get`, "inputTypes") = c('_p_BeagleResourceList')
class(`BeagleResourceList_list_get`) = c("SWIGFunction", class('BeagleResourceList_list_get'))

# Start of BeagleResourceList_length_set

`BeagleResourceList_length_set` = function(self, s_length)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_length = as.integer(s_length);
  
  if(length(s_length) > 1) {
    warning("using only the first element of s_length");
  };
  
  ;.Call('R_swig_BeagleResourceList_length_set', self, s_length, PACKAGE='beagle');
  
}

attr(`BeagleResourceList_length_set`, 'returnType') = 'void'
attr(`BeagleResourceList_length_set`, "inputTypes") = c('_p_BeagleResourceList', 'integer')
class(`BeagleResourceList_length_set`) = c("SWIGFunction", class('BeagleResourceList_length_set'))

# Start of BeagleResourceList_length_get

`BeagleResourceList_length_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_BeagleResourceList_length_get', self, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`BeagleResourceList_length_get`, 'returnType') = 'integer'
attr(`BeagleResourceList_length_get`, "inputTypes") = c('_p_BeagleResourceList')
class(`BeagleResourceList_length_get`) = c("SWIGFunction", class('BeagleResourceList_length_get'))

# Start of new_BeagleResourceList

`BeagleResourceList` = function()
{
  ;ans = .Call('R_swig_new_BeagleResourceList', PACKAGE='beagle');
  ans <- new("_p_BeagleResourceList", ref=ans) ;
  
  reg.finalizer(ans@ref, delete_BeagleResourceList)
  ans
  
}

attr(`BeagleResourceList`, 'returnType') = '_p_BeagleResourceList'
class(`BeagleResourceList`) = c("SWIGFunction", class('BeagleResourceList'))

# Start of delete_BeagleResourceList

`delete_BeagleResourceList` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_delete_BeagleResourceList', self, PACKAGE='beagle');
  
}

attr(`delete_BeagleResourceList`, 'returnType') = 'void'
attr(`delete_BeagleResourceList`, "inputTypes") = c('_p_BeagleResourceList')
class(`delete_BeagleResourceList`) = c("SWIGFunction", class('delete_BeagleResourceList'))

# Start of accessor method for BeagleResourceList
setMethod('$', '_p_BeagleResourceList', function(x, name)

{
  accessorFuns = list('list' = BeagleResourceList_list_get, 'length' = BeagleResourceList_length_get);
  vaccessors = c('list', 'length');
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  if (is.na(match(name, vaccessors))) function(...){
    f(x, ...)
  } else f(x);
}


);
# end of accessor method for BeagleResourceList
# Start of accessor method for BeagleResourceList
setMethod('$<-', '_p_BeagleResourceList', function(x, name, value)

{
  accessorFuns = list('list' = BeagleResourceList_list_set, 'length' = BeagleResourceList_length_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
setMethod('[[<-', c('_p_BeagleResourceList', 'character'),function(x, i, j, ..., value)

{
  name = i;
  accessorFuns = list('list' = BeagleResourceList_list_set, 'length' = BeagleResourceList_length_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
# end of accessor method for BeagleResourceList
setMethod('delete', '_p_BeagleResourceList', function(obj) {delete_BeagleResourceList(obj)})
# Start definition of copy functions & methods for BeagleResourceList
CopyToR_BeagleResourceList = function(value, obj = new("BeagleResourceList"))
{
  obj@length = value$length;
  obj;
}



CopyToC_BeagleResourceList = function(value, obj)
{
  obj$length = value@length;
  obj
}



# Start definition of copy methods for BeagleResourceList
setMethod('copyToR', '_p_BeagleResourceList', CopyToR_BeagleResourceList);
setMethod('copyToC', 'BeagleResourceList', CopyToC_BeagleResourceList);

# End definition of copy methods for BeagleResourceList
# End definition of copy functions & methods for BeagleResourceList
# Start of beagleGetResourceList

`beagleGetResourceList` = function()
{
  ;ans = .Call('R_swig_beagleGetResourceList', PACKAGE='beagle');
  ans <- new("_p_BeagleResourceList", ref=ans) ;
  
  ans
  
}

attr(`beagleGetResourceList`, 'returnType') = '_p_BeagleResourceList'
class(`beagleGetResourceList`) = c("SWIGFunction", class('beagleGetResourceList'))

# Start of beagleCreateInstance

`beagleCreateInstance` = function(tipCount, partialsBufferCount, compactBufferCount, stateCount, patternCount, eigenBufferCount, matrixBufferCount, categoryCount, scaleBufferCount, resourceList, resourceCount, preferenceFlags, requirementFlags, returnInfo, .copy = FALSE)
{
  tipCount = as.integer(tipCount);
  
  if(length(tipCount) > 1) {
    warning("using only the first element of tipCount");
  };
  
  partialsBufferCount = as.integer(partialsBufferCount);
  
  if(length(partialsBufferCount) > 1) {
    warning("using only the first element of partialsBufferCount");
  };
  
  compactBufferCount = as.integer(compactBufferCount);
  
  if(length(compactBufferCount) > 1) {
    warning("using only the first element of compactBufferCount");
  };
  
  stateCount = as.integer(stateCount);
  
  if(length(stateCount) > 1) {
    warning("using only the first element of stateCount");
  };
  
  patternCount = as.integer(patternCount);
  
  if(length(patternCount) > 1) {
    warning("using only the first element of patternCount");
  };
  
  eigenBufferCount = as.integer(eigenBufferCount);
  
  if(length(eigenBufferCount) > 1) {
    warning("using only the first element of eigenBufferCount");
  };
  
  matrixBufferCount = as.integer(matrixBufferCount);
  
  if(length(matrixBufferCount) > 1) {
    warning("using only the first element of matrixBufferCount");
  };
  
  categoryCount = as.integer(categoryCount);
  
  if(length(categoryCount) > 1) {
    warning("using only the first element of categoryCount");
  };
  
  scaleBufferCount = as.integer(scaleBufferCount);
  
  if(length(scaleBufferCount) > 1) {
    warning("using only the first element of scaleBufferCount");
  };
  
  resourceList = as.integer(resourceList);
  resourceCount = as.integer(resourceCount);
  
  if(length(resourceCount) > 1) {
    warning("using only the first element of resourceCount");
  };
  
  preferenceFlags = as.integer(preferenceFlags);
  
  if(length(preferenceFlags) > 1) {
    warning("using only the first element of preferenceFlags");
  };
  
  requirementFlags = as.integer(requirementFlags);
  
  if(length(requirementFlags) > 1) {
    warning("using only the first element of requirementFlags");
  };
  
  if (inherits(returnInfo, "ExternalReference")) returnInfo = slot(returnInfo,"ref") 
  ;.Call('R_swig_beagleCreateInstance', tipCount, partialsBufferCount, compactBufferCount, stateCount, patternCount, eigenBufferCount, matrixBufferCount, categoryCount, scaleBufferCount, resourceList, resourceCount, preferenceFlags, requirementFlags, returnInfo, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleCreateInstance`, 'returnType') = 'integer'
attr(`beagleCreateInstance`, "inputTypes") = c('integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', '_p_BeagleInstanceDetails')
class(`beagleCreateInstance`) = c("SWIGFunction", class('beagleCreateInstance'))

# Start of beagleFinalizeInstance

`beagleFinalizeInstance` = function(instance, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  ;.Call('R_swig_beagleFinalizeInstance', instance, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleFinalizeInstance`, 'returnType') = 'integer'
attr(`beagleFinalizeInstance`, "inputTypes") = c('integer')
class(`beagleFinalizeInstance`) = c("SWIGFunction", class('beagleFinalizeInstance'))

# Start of beagleFinalize

`beagleFinalize` = function(.copy = FALSE)
{
  ;.Call('R_swig_beagleFinalize', as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleFinalize`, 'returnType') = 'integer'
class(`beagleFinalize`) = c("SWIGFunction", class('beagleFinalize'))

# Start of beagleSetTipStates

`beagleSetTipStates` = function(instance, tipIndex, inStates, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  tipIndex = as.integer(tipIndex);
  
  if(length(tipIndex) > 1) {
    warning("using only the first element of tipIndex");
  };
  
  inStates = as.integer(inStates);
  ;.Call('R_swig_beagleSetTipStates', instance, tipIndex, inStates, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleSetTipStates`, 'returnType') = 'integer'
attr(`beagleSetTipStates`, "inputTypes") = c('integer', 'integer', 'integer')
class(`beagleSetTipStates`) = c("SWIGFunction", class('beagleSetTipStates'))

# Start of beagleSetTipPartials

`beagleSetTipPartials` = function(instance, tipIndex, inPartials, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  tipIndex = as.integer(tipIndex);
  
  if(length(tipIndex) > 1) {
    warning("using only the first element of tipIndex");
  };
  
  
  ;.Call('R_swig_beagleSetTipPartials', instance, tipIndex, inPartials, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleSetTipPartials`, 'returnType') = 'integer'
attr(`beagleSetTipPartials`, "inputTypes") = c('integer', 'integer', 'numeric')
class(`beagleSetTipPartials`) = c("SWIGFunction", class('beagleSetTipPartials'))

# Start of beagleSetPartials

`beagleSetPartials` = function(instance, bufferIndex, inPartials, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  bufferIndex = as.integer(bufferIndex);
  
  if(length(bufferIndex) > 1) {
    warning("using only the first element of bufferIndex");
  };
  
  
  ;.Call('R_swig_beagleSetPartials', instance, bufferIndex, inPartials, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleSetPartials`, 'returnType') = 'integer'
attr(`beagleSetPartials`, "inputTypes") = c('integer', 'integer', 'numeric')
class(`beagleSetPartials`) = c("SWIGFunction", class('beagleSetPartials'))

# Start of beagleGetPartials

`beagleGetPartials` = function(instance, bufferIndex, scaleIndex, outPartials, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  bufferIndex = as.integer(bufferIndex);
  
  if(length(bufferIndex) > 1) {
    warning("using only the first element of bufferIndex");
  };
  
  scaleIndex = as.integer(scaleIndex);
  
  if(length(scaleIndex) > 1) {
    warning("using only the first element of scaleIndex");
  };
  
  
  ;.Call('R_swig_beagleGetPartials', instance, bufferIndex, scaleIndex, outPartials, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleGetPartials`, 'returnType') = 'integer'
attr(`beagleGetPartials`, "inputTypes") = c('integer', 'integer', 'integer', 'numeric')
class(`beagleGetPartials`) = c("SWIGFunction", class('beagleGetPartials'))

# Start of beagleSetEigenDecomposition

`beagleSetEigenDecomposition` = function(instance, eigenIndex, inEigenVectors, inInverseEigenVectors, inEigenValues, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  eigenIndex = as.integer(eigenIndex);
  
  if(length(eigenIndex) > 1) {
    warning("using only the first element of eigenIndex");
  };
  
  
  
  
  ;.Call('R_swig_beagleSetEigenDecomposition', instance, eigenIndex, inEigenVectors, inInverseEigenVectors, inEigenValues, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleSetEigenDecomposition`, 'returnType') = 'integer'
attr(`beagleSetEigenDecomposition`, "inputTypes") = c('integer', 'integer', 'numeric', 'numeric', 'numeric')
class(`beagleSetEigenDecomposition`) = c("SWIGFunction", class('beagleSetEigenDecomposition'))

# Start of beagleSetStateFrequencies

`beagleSetStateFrequencies` = function(instance, stateFrequenciesIndex, inStateFrequencies, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  stateFrequenciesIndex = as.integer(stateFrequenciesIndex);
  
  if(length(stateFrequenciesIndex) > 1) {
    warning("using only the first element of stateFrequenciesIndex");
  };
  
  
  ;.Call('R_swig_beagleSetStateFrequencies', instance, stateFrequenciesIndex, inStateFrequencies, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleSetStateFrequencies`, 'returnType') = 'integer'
attr(`beagleSetStateFrequencies`, "inputTypes") = c('integer', 'integer', 'numeric')
class(`beagleSetStateFrequencies`) = c("SWIGFunction", class('beagleSetStateFrequencies'))

# Start of beagleSetCategoryWeights

`beagleSetCategoryWeights` = function(instance, categoryWeightsIndex, inCategoryWeights, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  categoryWeightsIndex = as.integer(categoryWeightsIndex);
  
  if(length(categoryWeightsIndex) > 1) {
    warning("using only the first element of categoryWeightsIndex");
  };
  
  
  ;.Call('R_swig_beagleSetCategoryWeights', instance, categoryWeightsIndex, inCategoryWeights, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleSetCategoryWeights`, 'returnType') = 'integer'
attr(`beagleSetCategoryWeights`, "inputTypes") = c('integer', 'integer', 'numeric')
class(`beagleSetCategoryWeights`) = c("SWIGFunction", class('beagleSetCategoryWeights'))

# Start of beagleSetCategoryRates

`beagleSetCategoryRates` = function(instance, inCategoryRates, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  
  ;.Call('R_swig_beagleSetCategoryRates', instance, inCategoryRates, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleSetCategoryRates`, 'returnType') = 'integer'
attr(`beagleSetCategoryRates`, "inputTypes") = c('integer', 'numeric')
class(`beagleSetCategoryRates`) = c("SWIGFunction", class('beagleSetCategoryRates'))

# Start of beagleSetPatternWeights

`beagleSetPatternWeights` = function(instance, inPatternWeights, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  
  ;.Call('R_swig_beagleSetPatternWeights', instance, inPatternWeights, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleSetPatternWeights`, 'returnType') = 'integer'
attr(`beagleSetPatternWeights`, "inputTypes") = c('integer', 'numeric')
class(`beagleSetPatternWeights`) = c("SWIGFunction", class('beagleSetPatternWeights'))

# Start of beagleUpdateTransitionMatrices

`beagleUpdateTransitionMatrices` = function(instance, eigenIndex, probabilityIndices, firstDerivativeIndices, secondDerivativeIndices, edgeLengths, count, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  eigenIndex = as.integer(eigenIndex);
  
  if(length(eigenIndex) > 1) {
    warning("using only the first element of eigenIndex");
  };
  
  probabilityIndices = as.integer(probabilityIndices);
  firstDerivativeIndices = as.integer(firstDerivativeIndices);
  secondDerivativeIndices = as.integer(secondDerivativeIndices);
  
  count = as.integer(count);
  
  if(length(count) > 1) {
    warning("using only the first element of count");
  };
  
  ;.Call('R_swig_beagleUpdateTransitionMatrices', instance, eigenIndex, probabilityIndices, firstDerivativeIndices, secondDerivativeIndices, edgeLengths, count, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleUpdateTransitionMatrices`, 'returnType') = 'integer'
attr(`beagleUpdateTransitionMatrices`, "inputTypes") = c('integer', 'integer', 'integer', 'integer', 'integer', 'numeric', 'integer')
class(`beagleUpdateTransitionMatrices`) = c("SWIGFunction", class('beagleUpdateTransitionMatrices'))

# Start of beagleSetTransitionMatrix

`beagleSetTransitionMatrix` = function(instance, matrixIndex, inMatrix, paddedValue, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  matrixIndex = as.integer(matrixIndex);
  
  if(length(matrixIndex) > 1) {
    warning("using only the first element of matrixIndex");
  };
  
  
  
  ;.Call('R_swig_beagleSetTransitionMatrix', instance, matrixIndex, inMatrix, paddedValue, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleSetTransitionMatrix`, 'returnType') = 'integer'
attr(`beagleSetTransitionMatrix`, "inputTypes") = c('integer', 'integer', 'numeric', 'numeric')
class(`beagleSetTransitionMatrix`) = c("SWIGFunction", class('beagleSetTransitionMatrix'))

# Start of beagleGetTransitionMatrix

`beagleGetTransitionMatrix` = function(instance, matrixIndex, outMatrix, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  matrixIndex = as.integer(matrixIndex);
  
  if(length(matrixIndex) > 1) {
    warning("using only the first element of matrixIndex");
  };
  
  
  ;.Call('R_swig_beagleGetTransitionMatrix', instance, matrixIndex, outMatrix, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleGetTransitionMatrix`, 'returnType') = 'integer'
attr(`beagleGetTransitionMatrix`, "inputTypes") = c('integer', 'integer', 'numeric')
class(`beagleGetTransitionMatrix`) = c("SWIGFunction", class('beagleGetTransitionMatrix'))

# Start of beagleSetTransitionMatrices

`beagleSetTransitionMatrices` = function(instance, matrixIndices, inMatrices, paddedValues, count, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  matrixIndices = as.integer(matrixIndices);
  
  
  count = as.integer(count);
  
  if(length(count) > 1) {
    warning("using only the first element of count");
  };
  
  ;.Call('R_swig_beagleSetTransitionMatrices', instance, matrixIndices, inMatrices, paddedValues, count, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleSetTransitionMatrices`, 'returnType') = 'integer'
attr(`beagleSetTransitionMatrices`, "inputTypes") = c('integer', 'integer', 'numeric', 'numeric', 'integer')
class(`beagleSetTransitionMatrices`) = c("SWIGFunction", class('beagleSetTransitionMatrices'))

# Start of BeagleOperation_destinationPartials_set

`BeagleOperation_destinationPartials_set` = function(self, s_destinationPartials)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_destinationPartials = as.integer(s_destinationPartials);
  
  if(length(s_destinationPartials) > 1) {
    warning("using only the first element of s_destinationPartials");
  };
  
  ;.Call('R_swig_BeagleOperation_destinationPartials_set', self, s_destinationPartials, PACKAGE='beagle');
  
}

attr(`BeagleOperation_destinationPartials_set`, 'returnType') = 'void'
attr(`BeagleOperation_destinationPartials_set`, "inputTypes") = c('_p_BeagleOperation', 'integer')
class(`BeagleOperation_destinationPartials_set`) = c("SWIGFunction", class('BeagleOperation_destinationPartials_set'))

# Start of BeagleOperation_destinationPartials_get

`BeagleOperation_destinationPartials_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_BeagleOperation_destinationPartials_get', self, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`BeagleOperation_destinationPartials_get`, 'returnType') = 'integer'
attr(`BeagleOperation_destinationPartials_get`, "inputTypes") = c('_p_BeagleOperation')
class(`BeagleOperation_destinationPartials_get`) = c("SWIGFunction", class('BeagleOperation_destinationPartials_get'))

# Start of BeagleOperation_destinationScaleWrite_set

`BeagleOperation_destinationScaleWrite_set` = function(self, s_destinationScaleWrite)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_destinationScaleWrite = as.integer(s_destinationScaleWrite);
  
  if(length(s_destinationScaleWrite) > 1) {
    warning("using only the first element of s_destinationScaleWrite");
  };
  
  ;.Call('R_swig_BeagleOperation_destinationScaleWrite_set', self, s_destinationScaleWrite, PACKAGE='beagle');
  
}

attr(`BeagleOperation_destinationScaleWrite_set`, 'returnType') = 'void'
attr(`BeagleOperation_destinationScaleWrite_set`, "inputTypes") = c('_p_BeagleOperation', 'integer')
class(`BeagleOperation_destinationScaleWrite_set`) = c("SWIGFunction", class('BeagleOperation_destinationScaleWrite_set'))

# Start of BeagleOperation_destinationScaleWrite_get

`BeagleOperation_destinationScaleWrite_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_BeagleOperation_destinationScaleWrite_get', self, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`BeagleOperation_destinationScaleWrite_get`, 'returnType') = 'integer'
attr(`BeagleOperation_destinationScaleWrite_get`, "inputTypes") = c('_p_BeagleOperation')
class(`BeagleOperation_destinationScaleWrite_get`) = c("SWIGFunction", class('BeagleOperation_destinationScaleWrite_get'))

# Start of BeagleOperation_destinationScaleRead_set

`BeagleOperation_destinationScaleRead_set` = function(self, s_destinationScaleRead)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_destinationScaleRead = as.integer(s_destinationScaleRead);
  
  if(length(s_destinationScaleRead) > 1) {
    warning("using only the first element of s_destinationScaleRead");
  };
  
  ;.Call('R_swig_BeagleOperation_destinationScaleRead_set', self, s_destinationScaleRead, PACKAGE='beagle');
  
}

attr(`BeagleOperation_destinationScaleRead_set`, 'returnType') = 'void'
attr(`BeagleOperation_destinationScaleRead_set`, "inputTypes") = c('_p_BeagleOperation', 'integer')
class(`BeagleOperation_destinationScaleRead_set`) = c("SWIGFunction", class('BeagleOperation_destinationScaleRead_set'))

# Start of BeagleOperation_destinationScaleRead_get

`BeagleOperation_destinationScaleRead_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_BeagleOperation_destinationScaleRead_get', self, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`BeagleOperation_destinationScaleRead_get`, 'returnType') = 'integer'
attr(`BeagleOperation_destinationScaleRead_get`, "inputTypes") = c('_p_BeagleOperation')
class(`BeagleOperation_destinationScaleRead_get`) = c("SWIGFunction", class('BeagleOperation_destinationScaleRead_get'))

# Start of BeagleOperation_child1Partials_set

`BeagleOperation_child1Partials_set` = function(self, s_child1Partials)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_child1Partials = as.integer(s_child1Partials);
  
  if(length(s_child1Partials) > 1) {
    warning("using only the first element of s_child1Partials");
  };
  
  ;.Call('R_swig_BeagleOperation_child1Partials_set', self, s_child1Partials, PACKAGE='beagle');
  
}

attr(`BeagleOperation_child1Partials_set`, 'returnType') = 'void'
attr(`BeagleOperation_child1Partials_set`, "inputTypes") = c('_p_BeagleOperation', 'integer')
class(`BeagleOperation_child1Partials_set`) = c("SWIGFunction", class('BeagleOperation_child1Partials_set'))

# Start of BeagleOperation_child1Partials_get

`BeagleOperation_child1Partials_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_BeagleOperation_child1Partials_get', self, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`BeagleOperation_child1Partials_get`, 'returnType') = 'integer'
attr(`BeagleOperation_child1Partials_get`, "inputTypes") = c('_p_BeagleOperation')
class(`BeagleOperation_child1Partials_get`) = c("SWIGFunction", class('BeagleOperation_child1Partials_get'))

# Start of BeagleOperation_child1TransitionMatrix_set

`BeagleOperation_child1TransitionMatrix_set` = function(self, s_child1TransitionMatrix)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_child1TransitionMatrix = as.integer(s_child1TransitionMatrix);
  
  if(length(s_child1TransitionMatrix) > 1) {
    warning("using only the first element of s_child1TransitionMatrix");
  };
  
  ;.Call('R_swig_BeagleOperation_child1TransitionMatrix_set', self, s_child1TransitionMatrix, PACKAGE='beagle');
  
}

attr(`BeagleOperation_child1TransitionMatrix_set`, 'returnType') = 'void'
attr(`BeagleOperation_child1TransitionMatrix_set`, "inputTypes") = c('_p_BeagleOperation', 'integer')
class(`BeagleOperation_child1TransitionMatrix_set`) = c("SWIGFunction", class('BeagleOperation_child1TransitionMatrix_set'))

# Start of BeagleOperation_child1TransitionMatrix_get

`BeagleOperation_child1TransitionMatrix_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_BeagleOperation_child1TransitionMatrix_get', self, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`BeagleOperation_child1TransitionMatrix_get`, 'returnType') = 'integer'
attr(`BeagleOperation_child1TransitionMatrix_get`, "inputTypes") = c('_p_BeagleOperation')
class(`BeagleOperation_child1TransitionMatrix_get`) = c("SWIGFunction", class('BeagleOperation_child1TransitionMatrix_get'))

# Start of BeagleOperation_child2Partials_set

`BeagleOperation_child2Partials_set` = function(self, s_child2Partials)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_child2Partials = as.integer(s_child2Partials);
  
  if(length(s_child2Partials) > 1) {
    warning("using only the first element of s_child2Partials");
  };
  
  ;.Call('R_swig_BeagleOperation_child2Partials_set', self, s_child2Partials, PACKAGE='beagle');
  
}

attr(`BeagleOperation_child2Partials_set`, 'returnType') = 'void'
attr(`BeagleOperation_child2Partials_set`, "inputTypes") = c('_p_BeagleOperation', 'integer')
class(`BeagleOperation_child2Partials_set`) = c("SWIGFunction", class('BeagleOperation_child2Partials_set'))

# Start of BeagleOperation_child2Partials_get

`BeagleOperation_child2Partials_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_BeagleOperation_child2Partials_get', self, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`BeagleOperation_child2Partials_get`, 'returnType') = 'integer'
attr(`BeagleOperation_child2Partials_get`, "inputTypes") = c('_p_BeagleOperation')
class(`BeagleOperation_child2Partials_get`) = c("SWIGFunction", class('BeagleOperation_child2Partials_get'))

# Start of BeagleOperation_child2TransitionMatrix_set

`BeagleOperation_child2TransitionMatrix_set` = function(self, s_child2TransitionMatrix)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  s_child2TransitionMatrix = as.integer(s_child2TransitionMatrix);
  
  if(length(s_child2TransitionMatrix) > 1) {
    warning("using only the first element of s_child2TransitionMatrix");
  };
  
  ;.Call('R_swig_BeagleOperation_child2TransitionMatrix_set', self, s_child2TransitionMatrix, PACKAGE='beagle');
  
}

attr(`BeagleOperation_child2TransitionMatrix_set`, 'returnType') = 'void'
attr(`BeagleOperation_child2TransitionMatrix_set`, "inputTypes") = c('_p_BeagleOperation', 'integer')
class(`BeagleOperation_child2TransitionMatrix_set`) = c("SWIGFunction", class('BeagleOperation_child2TransitionMatrix_set'))

# Start of BeagleOperation_child2TransitionMatrix_get

`BeagleOperation_child2TransitionMatrix_get` = function(self, .copy = FALSE)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_BeagleOperation_child2TransitionMatrix_get', self, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`BeagleOperation_child2TransitionMatrix_get`, 'returnType') = 'integer'
attr(`BeagleOperation_child2TransitionMatrix_get`, "inputTypes") = c('_p_BeagleOperation')
class(`BeagleOperation_child2TransitionMatrix_get`) = c("SWIGFunction", class('BeagleOperation_child2TransitionMatrix_get'))

# Start of new_BeagleOperation

`BeagleOperation` = function()
{
  ;ans = .Call('R_swig_new_BeagleOperation', PACKAGE='beagle');
  ans <- new("_p_BeagleOperation", ref=ans) ;
  
  reg.finalizer(ans@ref, delete_BeagleOperation)
  ans
  
}

attr(`BeagleOperation`, 'returnType') = '_p_BeagleOperation'
class(`BeagleOperation`) = c("SWIGFunction", class('BeagleOperation'))

# Start of delete_BeagleOperation

`delete_BeagleOperation` = function(self)
{
  if (inherits(self, "ExternalReference")) self = slot(self,"ref") 
  ;.Call('R_swig_delete_BeagleOperation', self, PACKAGE='beagle');
  
}

attr(`delete_BeagleOperation`, 'returnType') = 'void'
attr(`delete_BeagleOperation`, "inputTypes") = c('_p_BeagleOperation')
class(`delete_BeagleOperation`) = c("SWIGFunction", class('delete_BeagleOperation'))

# Start of accessor method for BeagleOperation
setMethod('$', '_p_BeagleOperation', function(x, name)

{
  accessorFuns = list('destinationPartials' = BeagleOperation_destinationPartials_get, 'destinationScaleWrite' = BeagleOperation_destinationScaleWrite_get, 'destinationScaleRead' = BeagleOperation_destinationScaleRead_get, 'child1Partials' = BeagleOperation_child1Partials_get, 'child1TransitionMatrix' = BeagleOperation_child1TransitionMatrix_get, 'child2Partials' = BeagleOperation_child2Partials_get, 'child2TransitionMatrix' = BeagleOperation_child2TransitionMatrix_get);
  vaccessors = c('destinationPartials', 'destinationScaleWrite', 'destinationScaleRead', 'child1Partials', 'child1TransitionMatrix', 'child2Partials', 'child2TransitionMatrix');
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name));
  f = accessorFuns[[idx]];
  if (is.na(match(name, vaccessors))) function(...){
    f(x, ...)
  } else f(x);
}


);
# end of accessor method for BeagleOperation
# Start of accessor method for BeagleOperation
setMethod('$<-', '_p_BeagleOperation', function(x, name, value)

{
  accessorFuns = list('destinationPartials' = BeagleOperation_destinationPartials_set, 'destinationScaleWrite' = BeagleOperation_destinationScaleWrite_set, 'destinationScaleRead' = BeagleOperation_destinationScaleRead_set, 'child1Partials' = BeagleOperation_child1Partials_set, 'child1TransitionMatrix' = BeagleOperation_child1TransitionMatrix_set, 'child2Partials' = BeagleOperation_child2Partials_set, 'child2TransitionMatrix' = BeagleOperation_child2TransitionMatrix_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
setMethod('[[<-', c('_p_BeagleOperation', 'character'),function(x, i, j, ..., value)

{
  name = i;
  accessorFuns = list('destinationPartials' = BeagleOperation_destinationPartials_set, 'destinationScaleWrite' = BeagleOperation_destinationScaleWrite_set, 'destinationScaleRead' = BeagleOperation_destinationScaleRead_set, 'child1Partials' = BeagleOperation_child1Partials_set, 'child1TransitionMatrix' = BeagleOperation_child1TransitionMatrix_set, 'child2Partials' = BeagleOperation_child2Partials_set, 'child2TransitionMatrix' = BeagleOperation_child2TransitionMatrix_set);
  ;        idx = pmatch(name, names(accessorFuns));
  if(is.na(idx)) 
  return(callNextMethod(x, name, value));
  f = accessorFuns[[idx]];
  f(x, value);
  x;
}


);
# end of accessor method for BeagleOperation
setMethod('delete', '_p_BeagleOperation', function(obj) {delete_BeagleOperation(obj)})
# Start definition of copy functions & methods for BeagleOperation
CopyToR_BeagleOperation = function(value, obj = new("BeagleOperation"))
{
  obj@destinationPartials = value$destinationPartials;
  obj@destinationScaleWrite = value$destinationScaleWrite;
  obj@destinationScaleRead = value$destinationScaleRead;
  obj@child1Partials = value$child1Partials;
  obj@child1TransitionMatrix = value$child1TransitionMatrix;
  obj@child2Partials = value$child2Partials;
  obj@child2TransitionMatrix = value$child2TransitionMatrix;
  obj;
}



CopyToC_BeagleOperation = function(value, obj)
{
  obj$destinationPartials = value@destinationPartials;
  obj$destinationScaleWrite = value@destinationScaleWrite;
  obj$destinationScaleRead = value@destinationScaleRead;
  obj$child1Partials = value@child1Partials;
  obj$child1TransitionMatrix = value@child1TransitionMatrix;
  obj$child2Partials = value@child2Partials;
  obj$child2TransitionMatrix = value@child2TransitionMatrix;
  obj
}



# Start definition of copy methods for BeagleOperation
setMethod('copyToR', '_p_BeagleOperation', CopyToR_BeagleOperation);
setMethod('copyToC', 'BeagleOperation', CopyToC_BeagleOperation);

# End definition of copy methods for BeagleOperation
# End definition of copy functions & methods for BeagleOperation
# Start of beagleUpdatePartials

`beagleUpdatePartials` = function(instance, operations, operationCount, cumulativeScaleIndex, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  if (inherits(operations, "ExternalReference")) operations = slot(operations,"ref") 
  operationCount = as.integer(operationCount);
  
  if(length(operationCount) > 1) {
    warning("using only the first element of operationCount");
  };
  
  cumulativeScaleIndex = as.integer(cumulativeScaleIndex);
  
  if(length(cumulativeScaleIndex) > 1) {
    warning("using only the first element of cumulativeScaleIndex");
  };
  
  ;.Call('R_swig_beagleUpdatePartials', instance, operations, operationCount, cumulativeScaleIndex, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleUpdatePartials`, 'returnType') = 'integer'
attr(`beagleUpdatePartials`, "inputTypes") = c('integer', '_p_BeagleOperation', 'integer', 'integer')
class(`beagleUpdatePartials`) = c("SWIGFunction", class('beagleUpdatePartials'))

# Start of beagleWaitForPartials

`beagleWaitForPartials` = function(instance, destinationPartials, destinationPartialsCount, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  destinationPartials = as.integer(destinationPartials);
  destinationPartialsCount = as.integer(destinationPartialsCount);
  
  if(length(destinationPartialsCount) > 1) {
    warning("using only the first element of destinationPartialsCount");
  };
  
  ;.Call('R_swig_beagleWaitForPartials', instance, destinationPartials, destinationPartialsCount, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleWaitForPartials`, 'returnType') = 'integer'
attr(`beagleWaitForPartials`, "inputTypes") = c('integer', 'integer', 'integer')
class(`beagleWaitForPartials`) = c("SWIGFunction", class('beagleWaitForPartials'))

# Start of beagleAccumulateScaleFactors

`beagleAccumulateScaleFactors` = function(instance, scaleIndices, count, cumulativeScaleIndex, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  scaleIndices = as.integer(scaleIndices);
  count = as.integer(count);
  
  if(length(count) > 1) {
    warning("using only the first element of count");
  };
  
  cumulativeScaleIndex = as.integer(cumulativeScaleIndex);
  
  if(length(cumulativeScaleIndex) > 1) {
    warning("using only the first element of cumulativeScaleIndex");
  };
  
  ;.Call('R_swig_beagleAccumulateScaleFactors', instance, scaleIndices, count, cumulativeScaleIndex, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleAccumulateScaleFactors`, 'returnType') = 'integer'
attr(`beagleAccumulateScaleFactors`, "inputTypes") = c('integer', 'integer', 'integer', 'integer')
class(`beagleAccumulateScaleFactors`) = c("SWIGFunction", class('beagleAccumulateScaleFactors'))

# Start of beagleRemoveScaleFactors

`beagleRemoveScaleFactors` = function(instance, scaleIndices, count, cumulativeScaleIndex, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  scaleIndices = as.integer(scaleIndices);
  count = as.integer(count);
  
  if(length(count) > 1) {
    warning("using only the first element of count");
  };
  
  cumulativeScaleIndex = as.integer(cumulativeScaleIndex);
  
  if(length(cumulativeScaleIndex) > 1) {
    warning("using only the first element of cumulativeScaleIndex");
  };
  
  ;.Call('R_swig_beagleRemoveScaleFactors', instance, scaleIndices, count, cumulativeScaleIndex, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleRemoveScaleFactors`, 'returnType') = 'integer'
attr(`beagleRemoveScaleFactors`, "inputTypes") = c('integer', 'integer', 'integer', 'integer')
class(`beagleRemoveScaleFactors`) = c("SWIGFunction", class('beagleRemoveScaleFactors'))

# Start of beagleResetScaleFactors

`beagleResetScaleFactors` = function(instance, cumulativeScaleIndex, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  cumulativeScaleIndex = as.integer(cumulativeScaleIndex);
  
  if(length(cumulativeScaleIndex) > 1) {
    warning("using only the first element of cumulativeScaleIndex");
  };
  
  ;.Call('R_swig_beagleResetScaleFactors', instance, cumulativeScaleIndex, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleResetScaleFactors`, 'returnType') = 'integer'
attr(`beagleResetScaleFactors`, "inputTypes") = c('integer', 'integer')
class(`beagleResetScaleFactors`) = c("SWIGFunction", class('beagleResetScaleFactors'))

# Start of beagleCopyScaleFactors

`beagleCopyScaleFactors` = function(instance, destScalingIndex, srcScalingIndex, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  destScalingIndex = as.integer(destScalingIndex);
  
  if(length(destScalingIndex) > 1) {
    warning("using only the first element of destScalingIndex");
  };
  
  srcScalingIndex = as.integer(srcScalingIndex);
  
  if(length(srcScalingIndex) > 1) {
    warning("using only the first element of srcScalingIndex");
  };
  
  ;.Call('R_swig_beagleCopyScaleFactors', instance, destScalingIndex, srcScalingIndex, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleCopyScaleFactors`, 'returnType') = 'integer'
attr(`beagleCopyScaleFactors`, "inputTypes") = c('integer', 'integer', 'integer')
class(`beagleCopyScaleFactors`) = c("SWIGFunction", class('beagleCopyScaleFactors'))

# Start of beagleCalculateRootLogLikelihoods

`beagleCalculateRootLogLikelihoods` = function(instance, bufferIndices, categoryWeightsIndices, stateFrequenciesIndices, cumulativeScaleIndices, count, outSumLogLikelihood, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  bufferIndices = as.integer(bufferIndices);
  categoryWeightsIndices = as.integer(categoryWeightsIndices);
  stateFrequenciesIndices = as.integer(stateFrequenciesIndices);
  cumulativeScaleIndices = as.integer(cumulativeScaleIndices);
  count = as.integer(count);
  
  if(length(count) > 1) {
    warning("using only the first element of count");
  };
  
  
  ;.Call('R_swig_beagleCalculateRootLogLikelihoods', instance, bufferIndices, categoryWeightsIndices, stateFrequenciesIndices, cumulativeScaleIndices, count, outSumLogLikelihood, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleCalculateRootLogLikelihoods`, 'returnType') = 'integer'
attr(`beagleCalculateRootLogLikelihoods`, "inputTypes") = c('integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'numeric')
class(`beagleCalculateRootLogLikelihoods`) = c("SWIGFunction", class('beagleCalculateRootLogLikelihoods'))

# Start of beagleCalculateEdgeLogLikelihoods

`beagleCalculateEdgeLogLikelihoods` = function(instance, parentBufferIndices, childBufferIndices, probabilityIndices, firstDerivativeIndices, secondDerivativeIndices, categoryWeightsIndices, stateFrequenciesIndices, cumulativeScaleIndices, count, outSumLogLikelihood, outSumFirstDerivative, outSumSecondDerivative, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  parentBufferIndices = as.integer(parentBufferIndices);
  childBufferIndices = as.integer(childBufferIndices);
  probabilityIndices = as.integer(probabilityIndices);
  firstDerivativeIndices = as.integer(firstDerivativeIndices);
  secondDerivativeIndices = as.integer(secondDerivativeIndices);
  categoryWeightsIndices = as.integer(categoryWeightsIndices);
  stateFrequenciesIndices = as.integer(stateFrequenciesIndices);
  cumulativeScaleIndices = as.integer(cumulativeScaleIndices);
  count = as.integer(count);
  
  if(length(count) > 1) {
    warning("using only the first element of count");
  };
  
  
  
  
  ;.Call('R_swig_beagleCalculateEdgeLogLikelihoods', instance, parentBufferIndices, childBufferIndices, probabilityIndices, firstDerivativeIndices, secondDerivativeIndices, categoryWeightsIndices, stateFrequenciesIndices, cumulativeScaleIndices, count, outSumLogLikelihood, outSumFirstDerivative, outSumSecondDerivative, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleCalculateEdgeLogLikelihoods`, 'returnType') = 'integer'
attr(`beagleCalculateEdgeLogLikelihoods`, "inputTypes") = c('integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'numeric', 'numeric', 'numeric')
class(`beagleCalculateEdgeLogLikelihoods`) = c("SWIGFunction", class('beagleCalculateEdgeLogLikelihoods'))

# Start of beagleGetSiteLogLikelihoods

`beagleGetSiteLogLikelihoods` = function(instance, outLogLikelihoods, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  
  ;.Call('R_swig_beagleGetSiteLogLikelihoods', instance, outLogLikelihoods, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleGetSiteLogLikelihoods`, 'returnType') = 'integer'
attr(`beagleGetSiteLogLikelihoods`, "inputTypes") = c('integer', 'numeric')
class(`beagleGetSiteLogLikelihoods`) = c("SWIGFunction", class('beagleGetSiteLogLikelihoods'))

# Start of beagleGetSiteDerivatives

`beagleGetSiteDerivatives` = function(instance, outFirstDerivatives, outSecondDerivatives, .copy = FALSE)
{
  instance = as.integer(instance);
  
  if(length(instance) > 1) {
    warning("using only the first element of instance");
  };
  
  
  
  ;.Call('R_swig_beagleGetSiteDerivatives', instance, outFirstDerivatives, outSecondDerivatives, as.logical(.copy), PACKAGE='beagle');
  
}

attr(`beagleGetSiteDerivatives`, 'returnType') = 'integer'
attr(`beagleGetSiteDerivatives`, "inputTypes") = c('integer', 'numeric', 'numeric')
class(`beagleGetSiteDerivatives`) = c("SWIGFunction", class('beagleGetSiteDerivatives'))

# Start of new_BeagleOperationArray

`new_BeagleOperationArray` = function(nelements)
{
  nelements = as.integer(nelements);
  
  if(length(nelements) > 1) {
    warning("using only the first element of nelements");
  };
  
  ;ans = .Call('R_swig_new_BeagleOperationArray', nelements, PACKAGE='beagle');
  ans <- new("_p_BeagleOperation", ref=ans) ;
  
  ans
  
}

attr(`new_BeagleOperationArray`, 'returnType') = '_p_BeagleOperation'
attr(`new_BeagleOperationArray`, "inputTypes") = c('integer')
class(`new_BeagleOperationArray`) = c("SWIGFunction", class('new_BeagleOperationArray'))

# Start of delete_BeagleOperationArray

`delete_BeagleOperationArray` = function(ary)
{
  if (inherits(ary, "ExternalReference")) ary = slot(ary,"ref") 
  ;.Call('R_swig_delete_BeagleOperationArray', ary, PACKAGE='beagle');
  
}

attr(`delete_BeagleOperationArray`, 'returnType') = 'void'
attr(`delete_BeagleOperationArray`, "inputTypes") = c('_p_BeagleOperation')
class(`delete_BeagleOperationArray`) = c("SWIGFunction", class('delete_BeagleOperationArray'))

# Start of BeagleOperationArray_getitem

`BeagleOperationArray_getitem` = function(ary, index, .copy = FALSE)
{
  if (inherits(ary, "ExternalReference")) ary = slot(ary,"ref") 
  index = as.integer(index);
  
  if(length(index) > 1) {
    warning("using only the first element of index");
  };
  
  ;ans = .Call('R_swig_BeagleOperationArray_getitem', ary, index, as.logical(.copy), PACKAGE='beagle');
  ans <- new("_p_BeagleOperation", ref=ans);
  
  ans
  
}

attr(`BeagleOperationArray_getitem`, 'returnType') = '_p_BeagleOperation'
attr(`BeagleOperationArray_getitem`, "inputTypes") = c('_p_BeagleOperation', 'integer')
class(`BeagleOperationArray_getitem`) = c("SWIGFunction", class('BeagleOperationArray_getitem'))

# Start of BeagleOperationArray_setitem

`BeagleOperationArray_setitem` = function(ary, index, value)
{
  if (inherits(ary, "ExternalReference")) ary = slot(ary,"ref") 
  index = as.integer(index);
  
  if(length(index) > 1) {
    warning("using only the first element of index");
  };
  
  if (inherits(value, "ExternalReference")) value = slot(value,"ref") 
  ;.Call('R_swig_BeagleOperationArray_setitem', ary, index, value, PACKAGE='beagle');
  
}

attr(`BeagleOperationArray_setitem`, 'returnType') = 'void'
attr(`BeagleOperationArray_setitem`, "inputTypes") = c('_p_BeagleOperation', 'integer', '_p_BeagleOperation')
class(`BeagleOperationArray_setitem`) = c("SWIGFunction", class('BeagleOperationArray_setitem'))


